-- AlterTable
ALTER TABLE "User" ALTER COLUMN "weight" DROP NOT NULL,
ALTER COLUMN "weight" SET DATA TYPE TEXT,
ALTER COLUMN "height" DROP NOT NULL,
ALTER COLUMN "age" DROP NOT NULL,
ALTER COLUMN "dailyCalories" DROP NOT NULL,
ALTER COLUMN "dailyCalories" SET DEFAULT 2000,
ALTER COLUMN "fitnessGoal" DROP NOT NULL,
ALTER COLUMN "fitnessGoal" SET DEFAULT 'MAINTAIN',
ALTER COLUMN "activityLevel" DROP NOT NULL,
ALTER COLUMN "activityLevel" SET DEFAULT 'MODERATE';
