-- AlterTable
ALTER TABLE "Workout" ADD COLUMN     "calories" DOUBLE PRECISION,
ADD COLUMN     "date" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "exercise" TEXT,
ADD COLUMN     "reps" INTEGER,
ADD COLUMN     "sets" INTEGER,
ADD COLUMN     "weight" DOUBLE PRECISION;
